==== Business Requirement
MitziCom provides hosting and cloud services to a variety of clients from medium-sized companies to enterprise giants.
MitziCom want to lead a 30 to 40 hour proof-of-concept(POC) using Red Hat Ansible Tower.
The purpose of the POC is to determine the feasiblity of using Ansible Tower as a CI/CD tool for autumating continuous deployment of an internal three-tier application on QA and production environemnts.

The use case for this assignment is that MitziCom is pleased with the initial work and wants to move forward with deploying Red Hat
Ansible Engine more widely. It also sees potential value in deploying Red Hat Ansible Tower.

==== Design Ansible Tower workflow job template
1. Provision instances in the OpenStack QA environemnt
2. Deploy the application in the QA environment
3. Run the smoke test to verify the  application
   3.1 Clean up if the test fails
4. Provision instances on AWS 
5. Deploy the application in the production environment
6. Run the smoke test to verify the application
